# Generated by Django 4.2.4 on 2023-10-05 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('banner_type', models.IntegerField(choices=[(1, 'Banner-1'), (2, 'Banner-2'), (3, 'Banner-3'), (4, 'Banner-4'), (5, 'Banner-5'), (6, 'Banner-6'), (7, 'Banner-7'), (8, 'Banner-8'), (9, 'Banner-9'), (10, 'Banner-10'), (11, 'Banner-11')], default=1, unique=True)),
                ('header', models.CharField(max_length=130)),
                ('text_1', models.CharField(max_length=130)),
                ('text_2', models.CharField(max_length=130)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('shop_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
