# Generated by Django 4.2.4 on 2023-10-08 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_banner_is_active_brand_is_active_category_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=130)),
                ('slug', models.SlugField(blank=True, max_length=130, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField(default=0)),
                ('discount_price', models.FloatField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('gst_price', models.FloatField(default=0)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subcategory')),
            ],
            options={
                'unique_together': {('category', 'name', 'brand')},
            },
        ),
    ]
