# Generated by Django 4.2.4 on 2023-10-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
