# Generated by Django 4.2.4 on 2023-10-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_dealsoffer_off_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gst_price',
        ),
    ]
